/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:736435:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList1:736435:

public void btn_OpenDebugWindow_click1(GButton source, GEvent event) { //_CODE_:btn_OpenDebugWindows2:934461:
  println("btn_OpenDebugWindows2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btn_OpenDebugWindows2:934461:

public void btn_RefreshCOMPorts_click1(GButton source, GEvent event) { //_CODE_:btn_RefreshCOMPorts:748469:
  dropList1.setItems(Serial.list(), 0);
} //_CODE_:btn_RefreshCOMPorts:748469:

public void btn_connect_click1(GButton source, GEvent event) { //_CODE_:btn_connect:750775:
  connectToPort();
} //_CODE_:btn_connect:750775:

public void btn_disconnect_click1(GButton source, GEvent event) { //_CODE_:btn_disconnect:746234:
  println("btn_disconnect - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btn_disconnect:746234:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:364693:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield2:364693:

public void textfield3_change1(GTextField source, GEvent event) { //_CODE_:textfield3:630637:
  println("textfield3 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield3:630637:

public void ta_importedGCode_change1(GTextArea source, GEvent event) { //_CODE_:ta_importedGCode:479375:
  println("ta_importedGCode - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:ta_importedGCode:479375:

public void ta_cleanedGCode_change1(GTextArea source, GEvent event) { //_CODE_:ta_cleanedGCode:317711:
  println("ta_cleanedGCode - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:ta_cleanedGCode:317711:

public void btn_loadGCodeFile_click1(GButton source, GEvent event) { //_CODE_:btn_loadGCodeFile:639155:
  println("btn_loadGCodeFile - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btn_loadGCodeFile:639155:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Main");
  dropList1 = new GDropList(this, 10, 40, 90, 80, 3);
  dropList1.setItems(loadStrings("list_736435"), 0);
  dropList1.addEventHandler(this, "dropList1_click1");
  btn_OpenDebugWindows2 = new GButton(this, 430, 570, 60, 20);
  btn_OpenDebugWindows2.setText("Debug");
  btn_OpenDebugWindows2.addEventHandler(this, "btn_OpenDebugWindow_click1");
  btn_RefreshCOMPorts = new GButton(this, 10, 10, 90, 20);
  btn_RefreshCOMPorts.setText("refresh");
  btn_RefreshCOMPorts.addEventHandler(this, "btn_RefreshCOMPorts_click1");
  btn_connect = new GButton(this, 10, 70, 90, 20);
  btn_connect.setText("connect");
  btn_connect.addEventHandler(this, "btn_connect_click1");
  btn_disconnect = new GButton(this, 10, 100, 90, 20);
  btn_disconnect.setText("disconnect");
  btn_disconnect.addEventHandler(this, "btn_disconnect_click1");
  textfield2 = new GTextField(this, 200, 10, 110, 40, G4P.SCROLLBARS_NONE);
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
  textfield3 = new GTextField(this, 200, 60, 110, 40, G4P.SCROLLBARS_NONE);
  textfield3.setOpaque(true);
  textfield3.addEventHandler(this, "textfield3_change1");
  label1 = new GLabel(this, 152, 16, 40, 30);
  label1.setText("X:");
  label1.setOpaque(false);
  label2 = new GLabel(this, 151, 65, 40, 28);
  label2.setText("Y");
  label2.setOpaque(false);
  ta_importedGCode = new GTextArea(this, 10, 180, 260, 370, G4P.SCROLLBARS_VERTICAL_ONLY);
  ta_importedGCode.setOpaque(true);
  ta_importedGCode.addEventHandler(this, "ta_importedGCode_change1");
  ta_cleanedGCode = new GTextArea(this, 290, 180, 260, 370, G4P.SCROLLBARS_VERTICAL_ONLY);
  ta_cleanedGCode.setOpaque(true);
  ta_cleanedGCode.addEventHandler(this, "ta_cleanedGCode_change1");
  btn_loadGCodeFile = new GButton(this, 10, 560, 80, 30);
  btn_loadGCodeFile.setText("load GCode");
  btn_loadGCodeFile.addEventHandler(this, "btn_loadGCodeFile_click1");
}

// Variable declarations 
// autogenerated do not edit
GDropList dropList1; 
GButton btn_OpenDebugWindows2; 
GButton btn_RefreshCOMPorts; 
GButton btn_connect; 
GButton btn_disconnect; 
GTextField textfield2; 
GTextField textfield3; 
GLabel label1; 
GLabel label2; 
GTextArea ta_importedGCode; 
GTextArea ta_cleanedGCode; 
GButton btn_loadGCodeFile; 

